# "$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "os"
    style = "plain"
    foreground = "blue"
    background = "transparent"
    # template = "{{ if .WSL }}WSL at {{ end }}{{.Icon}} "
    template = '{{.Icon}}  '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'
    # template = '{{ .Path }}{{if eq .Path "~" }}>{{end}}'

    [blocks.segments.properties]
      style = 'full'

    [[blocks.segments]]
      type = 'git'
      style = 'plain'
      foreground = 'p:grey'
      background = 'transparent'
      template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
      #template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"

      [blocks.segments.properties]
        branch_icon = ''
        commit_icon = '@'
        fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hide'


  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

  # to identify the shell used
  # [[blocks.segments]]
  #   type = "shell"
  #   style = "plain"
  #   foreground = 'green'
  #   background = 'transparent'
  #   template = '{{ .Name }} '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = ' {{if eq .Shell "bash"}}$ {{else}}❯ {{end}}'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '

[pallete]
grey = '#6c6c6c'
